### ISSUE TITLE
Login module

### ISSUE THREAD

**Issue by AtulDwivedi** [AtulDwivedi/shop-cart#1]
# Task list

- [x] Retrieve user credentials from form submission
- [x] Retrieve user credentials from back-end system
- [x] Check the validity of the user by checking form data against back-end data
- [x] If user is valid, put `userName` as session attribute and navigate user to home page
- [x] Else navigate user back to login page with proper error message
- [x] **Test the enhancement**
## References
* [Help](http://www.javaworld.com/article/2072937/java-web-development/solving-the-logout-problem-properly-and-elegantly.html)

**Comment by AtulDwivedi** [comment]
It's done @PreetiKumari21 @smitlad

**Comment by smitlad** [comment]
It's done
